export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/hookuseloaddrop1/index',
    'pages/hookuseloadpage1/index',
    'pages/hookuseloadrefresh1/index',
    'pages/hookuserequest2/index',
    'pages/hookuserequest1/index',
    'pages/hookuseasync3/index',
    'pages/hookuseasync2/index',
    'pages/hookuseasync1/index',
    'pages/hookuseloading2/index',
    'pages/hookuseloading1/index',
    'pages/hookusetoggle2/index',
    'pages/hookusevisible2/index',
    'pages/hookusevisible1/index',
    'pages/hookusetoggle1/index',
    'pages/home/index',
    'pages/category/index',
    'pages/car/index',
    'pages/user/index',
    'pages/store/index',
    'pages/hook/index',
    'pages/searchCorpus/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    color: 'black',
    selectedColor: '#000000',
    backgroundColor: '#FAFAFA',
    borderStyle: 'white',
    position: 'bottom',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
      },
      {
        pagePath: 'pages/category/index',
        text: '分类',
      },
      {
        pagePath: 'pages/car/index',
        text: '购物车',
      },
      {
        pagePath: 'pages/user/index',
        text: '我的',
      },
    ],
  },
});
